// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZhzRFepwGQq-pZamcqpy5mNuGWpHaj8Q',
    appId: '1:533438220763:web:d82753a856177a5533fffe',
    messagingSenderId: '533438220763',
    projectId: 'inhouseglowsafe',
    authDomain: 'inhouseglowsafe.firebaseapp.com',
    storageBucket: 'inhouseglowsafe.appspot.com',
    measurementId: 'G-71EYZ2K5NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNCftEtsoAhLEcQr9vR30ci3vJigo_kx8',
    appId: '1:533438220763:android:5245d204cb68966333fffe',
    messagingSenderId: '533438220763',
    projectId: 'inhouseglowsafe',
    storageBucket: 'inhouseglowsafe.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZhzRFepwGQq-pZamcqpy5mNuGWpHaj8Q',
    appId: '1:533438220763:web:08d4d94193458c0e33fffe',
    messagingSenderId: '533438220763',
    projectId: 'inhouseglowsafe',
    authDomain: 'inhouseglowsafe.firebaseapp.com',
    storageBucket: 'inhouseglowsafe.appspot.com',
    measurementId: 'G-N24ERT46DZ',
  );
}
